<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body style="white-space:initial;margin: 0; padding: 0;">
    <span style="font-family:"Calibri">
        <p>Dear GHAP User,</p>
        <p>You request to postpone a scheduled stop on your idle resources has been successfully submitted.</p>
        <p>If you have any questions, please email GHAP Customer Support at <a href="mailto:$adminEmail$">$adminEmail$</a>.<br/>Thanks,<br/>GHAP System Administration</p>
    </span>
    </body>
</html>





