<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body style="white-space:initial;margin: 0; padding: 0;font-family: Helvetica, sans-serif;">
        <p>Dear $user.fullName$,</p>
        <p>Welcome to the GLOBAL HEALTH Analytics Platform (GHAP).  Please save this email for future reference.</p>
        <p>You user name is $user.name$ and your password is $user.password$</p>
        <p>To login to the system, go to <a href="https://www.ghap.io">https://www.ghap.io</a>.</p>
        <p>If you have any difficulty logging in, please let us know.</p>
        <p>Thanks,</p>
        <p>GHAP System Administration</p>
    </body>
</html>