<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body style="white-space:initial;margin: 0; padding: 0;font-family: Helvetica, sans-serif;">
        <p>Dear $user.fullName$,</p>
        <p>Your password to the GLOBAL HEALTH Analytics Platform (GHAP) will expire in $days$ days.</p>
        <p>Please login to the system and reset your password by selecting the Account link at the top of the page.</p>
        <p>If you encounter a problem, please <a href="mailto:$adminEmail$">let us know</a>.</p>
        <p>Thanks,</p>
        <p>GHAP System Administration</p>
    </body>
</html>