<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body style="white-space:initial;margin: 0; padding: 0;font-family: Helvetica, sans-serif;">
        <p>Dear $user.fullName$,</p>
        <p>To update account, select the button below:<br><br><a href="$url$"><img src="$baseUrl$/images/reset-password-btn.png" border="0" /></a></p>
        <!--<a href="mailto:$adminEmail$">$adminEmail$</a>-->
        <p>Thanks,</p>
        <p>GHAP System Administration</p>
    </body>
</html>