<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body style="white-space:initial;margin: 0; padding: 0;font-family: Helvetica, sans-serif;">
<p>Dear $user.fullName$,</p>
<p>This email confirms we changed your "password" to the GHAP system.</p>
<p>Your new password is $user.password$</p>
<p><a href="mailto:$adminEmail$">$adminEmail$</a></p>
<p>Thanks,</p>
<p>GHAP System Administration</p>
</body>
</html>